# Generated by Django 4.0.6 on 2022-08-01 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Debtors',
            new_name='Debtor',
        ),
    ]
