# Generated by Django 4.1 on 2022-08-10 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contention',
            name='guardian_contending',
            field=models.ForeignKey(limit_choices_to={'is_guardian': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='schooldetail',
            name='school',
            field=models.ForeignKey(limit_choices_to={'is_school_admin': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
