# Generated by Django 4.1 on 2022-08-08 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SchoolDetails',
            new_name='SchoolDetail',
        ),
    ]
