# Generated by Django 4.1 on 2022-08-10 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_contention_guardian_contending_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debtor',
            name='school_name',
        ),
    ]
