# Generated by Django 4.0.6 on 2022-08-12 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_debtor_gender_alter_schooldetail_copy_of_cac'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schooldetail',
            name='copy_of_CAC',
        ),
    ]
